services:

  mysql:
    image: mysql:8.0
    container_name: ems-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ../newdemo
      dockerfile: Dockerfile

    image: ems-backend:latest
    container_name: ems-backend

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    image: ems-frontend:latest
    container_name: ems-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"

volumes:
  mysql_data: